insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (397121, 8, 'Omri Naftali', 'innovative, stylish and mind-bending', null);  # 397121 "Matrix" 1993
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (644, 7, 'Omri Naftali', 'funny, great actors', null);  # 644 10 Things I Hate About You 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (849, 6, 'Omri Naftali', 'cute sequal with charming moments', null);  # 849 101 Dalmatians II: Patch's London Adventure 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1038, 6, 'Omri Naftali', 'charming, funny and heart-warming', null);  # 1038 13 Going On 30 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (10830, 9, 'Omri Naftali', 'great blend of horror and sci-fi', null);  # 10830 Alien 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14132, 8, 'Omri Naftali', 'very funny sequal', null);  # 14132 American Pie 2 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30959, 10, 'Omri Naftali', 'one of the best action movies out there', null);  # 30959 Batman Begins 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30965, 9, 'Omri Naftali', 'great action, Val Kilmer does great', null);  # 30965 Batman Forever 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30967, 9, 'Omri Naftali', 'amazing action, Michael Keaton is a great batman', null);  # 30967 Batman Returns 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (34077, 8, 'Omri Naftali', 'visually stunning and emotional', null);  # 34077 Benjamin Button 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (39551, 9, 'Omri Naftali', 'intense realistic war drama', null);  # 39551 Black Hawk Down 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40199, 10, 'Omri Naftali', 'iconic, visually incredible', null);  # 40199 Blade Runner 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56304, 9, 'Omri Naftali', 'crime epic with unforgettable performances', null);  # 56304 Casino 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56871, 10, 'Omri Naftali', 'one of my favourites, clever, funny and rewatchable', null);  # 56871 Catch Me If You Can 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (59578, 7, 'Omri Naftali', 'great dark quirky twist', null);  # 59578 Charlie and the Chocolate Factory 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66194, 8, 'Omri Naftali', 'funny, stylish, quatable', null);  # 66194 Clueless 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86263, 7, 'Omri Naftali', 'classic bond movie, yet not the best execution', null);  # 86263 Die Another Day 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (92573, 10, 'Omri Naftali', 'Connery makes a terrific bond', null);  # 92573 Dr. No 1962
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (97727, 8, 'Omri Naftali', 'whimsical and emotional', null);  # 97727 Edward Scissorhands 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (109421, 9, 'Omri Naftali', 'great recing action, back when the franchise was good', null);  # 109421 Fast and the Furious, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112290, 10, 'Omri Naftali', 'perfect twist, deep message', null);  # 112290 Fight Club 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (123849, 8, 'Omri Naftali', 'epic and powerfull', null);  # 123849 Gangs of New York 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130953, 9, 'Omri Naftali', 'iconic and stylish bond film', null);  # 130953 Goldfinger 1964
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131780, 10, 'Omri Naftali', 'oconic, riveting crime classic', null);  # 131780 Goodfellas 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131885, 7, 'Omri Naftali', 'fun and adventurous', null);  # 131885 Goonies, The 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139650, 10, 'Omri Naftali', 'magical and visually stunning', null);  # 139650 Harry Potter and the Chamber of Secrets 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139652, 10, 'Omri Naftali', 'magical and visually stunning', null);  # 139652 Harry Potter and the Goblet of Fire 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139653, 10, 'Omri Naftali', 'magical and visually stunning', null);  # 139653 Harry Potter and the Half-Blood Prince 2008
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139654, 10, 'Omri Naftali', 'magical and visually stunning', null);  # 139654 Harry Potter and the Order of the Phoenix 2007
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139655, 10, 'Omri Naftali', 'magical and visually stunning', null);  # 139655 Harry Potter and the Prisoner of Azkaban 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (139657, 10, 'Omri Naftali', 'magical and visually stunning', null);  # 139657 Harry Potter and the Sorcerer's Stone 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (142491, 7, 'Omri Naftali', 'fun charming action', null);  # 142491 Hellboy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158999, 8, 'Omri Naftali', 'great alien invasion action', null);  # 158999 Independence Day 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159172, 9, 'Omri Naftali', 'thrilling and fun action', null);  # 159172 Indiana Jones and the Last Crusade 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159175, 8, 'Omri Naftali', 'intense and exiting action', null);  # 159175 Indiana Jones and the Temple of Doom 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (159665, 10, 'Omri Naftali', 'a Tarantino master pieace', null);  # 159665 Inglorious Bastards 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (160524, 7, 'Omri Naftali', 'psuchological thriller, strong performances', null);  # 160524 Insomnia 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (162380, 9, 'Omri Naftali', 'great action and funny moments', null);  # 162380 Iron Man 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (165961, 8, 'Omri Naftali', 'suspenfull and rewatchable', null);  # 165961 Jaws 1975
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176711, 9, 'Omri Naftali', 'stylish, bloody and entertaining', null);  # 176711 Kill Bill: Vol. 1 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (176712, 9, 'Omri Naftali', 'great rich sequal', null);  # 176712 Kill Bill: Vol. 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177369, 8, 'Omri Naftali', 'darkly funny, De Niro does great', null);  # 177369 King of Comedy, The 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (185628, 8, 'Omri Naftali', 'epic, emotional and stunning', null);  # 185628 Last Samurai, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (189403, 8, 'Omri Naftali', 'darker grittier bond', null);  # 189403 Licence to Kill 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (192514, 8, 'Omri Naftali', 'fresh, decent debut for Roger Moore', null);  # 192514 Live and Let Die 1973
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194497, 9, 'Omri Naftali', 'epic fantasy with great pacing and visuals', null);  # 194497 Lord of the Rings: The Fellowship of the Ring, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194500, 10, 'Omri Naftali', 'grand conclusion with emotional impact', null);  # 194500 Lord of the Rings: The Return of the King, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194502, 9, 'Omri Naftali', 'strong middle chapter with great battles', null);  # 194502 Lord of the Rings: The Two Towers, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (203649, 6, 'Omri Naftali', 'fun bond film with classic action scenes', null);  # 203649 Man with the Golden Gun, The 1974
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210511, 8, 'Omri Naftali', 'clever twisty plot and strong performances', null);  # 210511 Memento 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (210739, 7, 'Omri Naftali', 'entertaining sci fi comedy with charm', null);  # 210739 Men in Black 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215876, 7, 'Omri Naftali', 'solid spy action with memorable stunts', null);  # 215876 Mission: Impossible 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215879, 6, 'Omri Naftali', 'decent sequel with some strong action', null);  # 215879 Mission: Impossible II 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (215880, 8, 'Omri Naftali', 'tense spy thriller with solid pacing', null);  # 215880 Mission: Impossible III 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (220805, 7, 'Omri Naftali', 'fun action comedy with good chemistry', null);  # 220805 Mr. and Mrs. Smith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238072, 10, 'Omri Naftali', 'stylish heist film with a great cast', null);  # 238072 Ocean's Eleven 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (238073, 6, 'Omri Naftali', 'weaker sequel but still entertaining', null);  # 238073 Ocean's Twelve 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (240521, 6, 'Omri Naftali', 'classic bond with an engaging plot', null);  # 240521 On Her Majesty's Secret Service 1969
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256631, 10, 'Omri Naftali', 'fun pirate adventure with humor', null);  # 256631 Pirates of the Caribbean 2 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (256632, 10, 'Omri Naftali', 'fantastic adventure with iconic characters', null);  # 256632 Pirates of the Caribbean: The Curse of the Black Pearl 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (263360, 7, 'Omri Naftali', 'charming romance with strong leads', null);  # 263360 Pretty Woman 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (267038, 10, 'Omri Naftali', 'stylish sharp dialogue and structure', null);  # 267038 Pulp Fiction 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (270971, 8, 'Omri Naftali', 'intense boxing drama with depth', null);  # 270971 Raging Bull 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (271095, 9, 'Omri Naftali', 'exciting adventure with iconic scenes', null);  # 271095 Raiders of the Lost Ark 1981
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276217, 9, 'Omri Naftali', 'stylish crime drama with great dialogue', null);  # 276217 Reservoir Dogs 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280270, 8, 'Omri Naftali', 'inspiring underdog boxing story', null);  # 280270 Rocky 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280281, 7, 'Omri Naftali', 'solid continuation of rocky saga', null);  # 280281 Rocky II 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280282, 7, 'Omri Naftali', 'entertaining sequel with heart', null);  # 280282 Rocky III 1982
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280284, 8, 'Omri Naftali', 'memorable rivalry and training scenes', null);  # 280284 Rocky IV 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (280305, 5, 'Omri Naftali', 'less impactful entry in the series', null);  # 280305 Rocky V 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289109, 9, 'Omri Naftali', 'gripping war drama with emotional depth', null);  # 289109 Saving Private Ryan 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291698, 9, 'Omri Naftali', 'dark crime thriller with strong acting', null);  # 291698 Se7en 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (297838, 10, 'Omri Naftali', 'moving prison drama with hope', null);  # 297838 Shawshank Redemption, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300229, 7, 'Omri Naftali', 'fun animated adventure with humor', null);  # 300229 Shrek 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (300230, 7, 'Omri Naftali', 'charming sequel with laughs', null);  # 300230 Shrek 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311037, 8, 'Omri Naftali', 'engaging superhero origin story', null);  # 311037 Spider-Man 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (311038, 8, 'Omri Naftali', 'strong sequel with emotional stakes', null);  # 311038 Spider-Man 2 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312150, 8, 'Omri Naftali', 'great family spy movie', null);  # 312150 Spy Kids 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312151, 8, 'Omri Naftali', 'funny, intertaining sequal', null);  # 312151 Spy Kids 2: Island of Lost Dreams 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (312152, 8, 'Omri Naftali', 'great humor and very entertaining', null);  # 312152 Spy Kids 3-D: Game Over 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313474, 5, 'Omri Naftali', 'uneven prequel with standout set pieces', null);  # 313474 Star Wars: Episode I - The Phantom Menace 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313476, 5, 'Omri Naftali', 'improved action but weak dialogue', null);  # 313476 Star Wars: Episode II - Attack of the Clones 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313477, 7, 'Omri Naftali', 'darker turn with a strong finale', null);  # 313477 Star Wars: Episode III - Revenge of the Sith 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313478, 10, 'Omri Naftali', 'genre defining space adventure with depth', null);  # 313478 Star Wars: Episode V - The Empire Strikes Back 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (313479, 8, 'Omri Naftali', 'satisfying conclusion with great set pieces', null);  # 313479 Star Wars: Episode VI - Return of the Jedi 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319602, 8, 'Omri Naftali', 'classic superhero tale with sincere tone', null);  # 319602 Superman 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (319613, 7, 'Omri Naftali', 'fun sequel with memorable villain confrontations', null);  # 319613 Superman II 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (326155, 9, 'Omri Naftali', 'haunting character study with striking imagery', null);  # 326155 Taxi Driver 1976
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (328272, 6, 'Omri Naftali', 'gentle dramedy with heartfelt moments', null);  # 328272 Terminal, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (333856, 9, 'Omri Naftali', 'sweeping romance with impressive spectacle', null);  # 333856 Titanic 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335336, 8, 'Omri Naftali', 'slick bond outing with solid action', null);  # 335336 Tomorrow Never Dies 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (335835, 9, 'Omri Naftali', 'iconic aerial action and unforgettable soundtrack', null);  # 335835 Top Gun 1986
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336445, 6, 'Omri Naftali', 'intense period drama with ok acting', null);  # 336445 Total Eclipse 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337166, 10, 'Omri Naftali', 'groundbreaking animation with heart and wit', null);  # 337166 Toy Story 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (351705, 7, 'Omri Naftali', 'gritty action drama with engaging momentum', null);  # 351705 Vengeance 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (368418, 6, 'Omri Naftali', 'bond adventure with mixed execution', null);  # 368418 World Is Not Enough, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (370017, 5, 'Omri Naftali', 'extreme action with uneven script', null);  # 370017 XXX 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (372233, 8, 'Omri Naftali', 'classic bond  with memorable settings', null);  # 372233 You Only Live Twice 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (120574, 9, 'Omri Naftali', 'iconic train showdown, tense', null);  # 120574 From Russia with Love 1963
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (332065, 8, 'Omri Naftali', 'stylish, great underwater action', null);  # 332065 Thunderball 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (85871, 6, 'Omri Naftali', 'memorable set pieces, not the best bond', null);  # 85871 Diamonds Are Forever 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218808, 5, 'Omri Naftali', 'sacrifices realism for spectacle', null);  # 218808 Moonraker 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117314, 8, 'Omri Naftali', 'grounded tense spy movie', null);  # 117314 For Your Eyes Only 1967
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (1529, 9, 'Omri Naftali', 'great pace, action and setting', null);  # 1529 2 Fast 2 Furious 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (117874, 10, 'Omri Naftali', 'incredible character develpment', null);  # 117874 Forrest Gump 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (138797, 7, 'Omri Naftali', 'goofy and quatable', null);  # 138797 Happy Gilmore 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (119358, 7, 'Omri Naftali', 'fun and charming', null);  # 119358 Freaky Friday 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (226939, 10, 'Omri Naftali', 'such stupid humor, that it takes a genius to write it', null);  # 226939 Naked Gun: From the Files of Police Squad!, The 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (80583, 9, 'Omri Naftali', 'meaningfull movie', null);  # 80583 Dead Poets Society 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (359297, 7, 'Omri Naftali', 'intense and visually griping', null);  # 359297 War of the Worlds 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (108760, 5, 'Omri Naftali', 'not the best superhero movie', null);  # 108760 Fantastic Four 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18979, 9, 'Omri Naftali', 'gripping and inspiring', null);  # 18979 Apollo 13 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (129185, 9, 'Omri Naftali', 'epic, emotional and visually spectacular', null);  # 129185 Gladiator 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26844, 8, 'Omri Naftali', 'ahead of its time', null);  # 26844 Back to the Future 1985
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (301540, 10, 'Omri Naftali', 'chilling, perfect acting', null);  # 301540 Silence of the Lambs, The 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (131665, 9, 'Omri Naftali', 'easily rewatchable, feel good, inspiring movie', null);  # 131665 Good Will Hunting 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (141544, 9, 'Omri Naftali', 'De Niro and Al Pachino', null);  # 141544 Heat 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (969, 10, 'Omri Naftali', 'perfect writing, courtroom drama', null);  # 969 12 Angry Men 1957
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (134077, 9, 'Omri Naftali', 'powerfull and emotional', null);  # 134077 Green Mile, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (9125, 10, 'Omri Naftali', 'gilarious parody', null);  # 9125 Airplane! 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (276085, 4, 'Omri Naftali', 'boring, slow pace', null);  # 276085 Requiem for a Dream 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (248878, 5, 'Omri Naftali', 'ok comedy, has funny parts', null);  # 248878 Parent Trap, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340901, 9, 'Omri Naftali', 'clever satire on media and identity', null);  # 340901 Truman Show, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (45128, 10, 'Omri Naftali', 'brilliant action', null);  # 45128 Bourne Identity, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235541, 8, 'Omri Naftali', 'emotional, very smart story', null);  # 235541 Notebook, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209133, 6, 'Omri Naftali', 'chick flick, has some very funny moments still', null);  # 209133 Mean Girls 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (46169, 8, 'Omri Naftali', 'very inspirational', null);  # 46169 Braveheart 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (130128, 9, 'Omri Naftali', 'smart crime movie', null);  # 130128 Godfather, The 1972
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (18960, 10, 'Omri Naftali', 'haunting war epic', null);  # 18960 Apocalypse Now 1979
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (158927, 9, 'Omri Naftali', 'really fun ation', null);  # 158927 Incredibles, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264146, 10, 'Omri Naftali', 'endlessly quatable and rewatchable', null);  # 264146 Princess Bride, The 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289558, 9, 'Omri Naftali', 'iconic crime saga', null);  # 289558 Scarface 1983
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (299073, 8, 'Omri Naftali', 'unsetteling and unforettable', null);  # 299073 Shining, The 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37178, 7, 'Omri Naftali', 'quirky, offbeat fun', null);  # 37178 Big Lebowski, The 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (45129, 10, 'Omri Naftali', 'another amazing entry to the franchise', null);  # 45129 Bourne Supremacy, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (90772, 9, 'Omri Naftali', 'mysterious and thought-provoking', null);  # 90772 Donnie Darko
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (66286, 10, 'Omri Naftali', 'inspiring basketball movie', null);  # 66286 Coach Carter 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (207157, 8, 'Omri Naftali', 'Jim Carrey leads a fun movie', null);  # 207157 Mask, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (254986, 9, 'Omri Naftali', 'incredible acting', null);  # 254986 Pianist, The 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (56373, 6, 'Omri Naftali', 'sweet, but not the best', null);  # 56373 Casper 1995
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (340652, 9, 'Omri Naftali', 'great action, Brad Pitt', null);  # 340652 Troy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (14145, 10, 'Omri Naftali', 'Thought-provoking, a smart outlook on society', null);  # 14145 American Psycho 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26847, 7, 'Omri Naftali', 'fun, western twist', null);  # 26847 Back to the Future Part III 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (37002, 7, 'Omri Naftali', 'goofy and heart-felt', null);  # 37002 Big Daddy 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (279841, 8, 'Omri Naftali', 'sharp and action-packed', null);  # 279841 RoboCop 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (32114, 9, 'Omri Naftali', 'inspiring and moving', null);  # 32114 Beautiful Mind, A 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (258860, 7, 'Omri Naftali', 'good blend of action and serfing', null);  # 258860 Point Break 1991
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (222339, 7, 'Omri Naftali', 'fun mix of action and humor', null);  # 222339 Mummy, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (112205, 8, 'Omri Naftali', 'action-packed sci-fi', null);  # 112205 Fifth Element, The 1997
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (309634, 7, 'Omri Naftali', 'a classic, yet not my favourite', null);  # 309634 Sound of Music, The 1965
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (121538, 10, 'Omri Naftali', 'captivating, great acting', null);  # 121538 Full Metal Jacket 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (133401, 9, 'Omri Naftali', 'fun groovy musical', null);  # 133401 Grease 1978
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (191246, 10, 'Omri Naftali', 'classic movie that no one can hate', null);  # 191246 Lion King, The 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (264158, 4, 'Omri Naftali', 'charming, yet not really my taste', null);  # 264158 Princess Diaries, The 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (291221, 6, 'Omri Naftali', 'not the best horror film in my opinion', null);  # 291221 Scream 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (30647, 8, 'Omri Naftali', 'some very iconic moments', null);  # 30647 Basic Instinct 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (272644, 9, 'Omri Naftali', 'fun, fell good movie', null);  # 272644 Ratatouille 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289666, 8, 'Omri Naftali', 'underrated, actually funny', null);  # 289666 Scary Movie 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (113504, 10, 'Omri Naftali', 'a timeless classic', null);  # 113504 Finding Nemo 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (86274, 9, 'Omri Naftali', 'great action, very quatable', null);  # 86274 Die Hard 1988
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (65764, 9, 'Omri Naftali', 'disturbing in a good way', null);  # 65764 Clockwork Orange, A 1971
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (128350, 8, 'Omri Naftali', 'fun teen comedy', null);  # 128350 Girl Next Door, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (195300, 7, 'Omri Naftali', 'warm and funny', null);  # 195300 Love Actually 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (111813, 10, 'Omri Naftali', 'a classic, very quatable', null);  # 111813 Few Good Men, A 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (163715, 9, 'Omri Naftali', 'stylish, fast paced heist', null);  # Italian Job, The 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (363780, 2, 'Omri Naftali', 'not funny at all in my opinion', null);  # 363780 White Chicks 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (336458, 9, 'Omri Naftali', 'mind-bending sci-fi', null);  # 336458 Total Recall 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (104699, 8, 'Omri Naftali', 'funny teem comedy', null);  # 104699 Eurotrip 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (173933, 9, 'Omri Naftali', 'iconic inspirational story', null);  # 173933 Karate Kid, The 1984
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2238, 7, 'Omri Naftali', 'visually striking action', null);  # 2238 300 2006
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (155070, 8, 'Omri Naftali', 'Will Smith does great', null);  # 155070 I, Robot 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (375827, 8, 'Omri Naftali', 'geniusly stuid movie', null);  # 375827 Zoolander 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (302329, 8, 'Omri Naftali', 'stylish, gritty and visually groundbraking', null);  # 302329 Sin City 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (310726, 8, 'Omri Naftali', 'tense fast-paced action', null);  # 310726 Speed 1994
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (148200, 9, 'Omri Naftali', 'classic holiday movie', null);  # 148200 Home Alone 1990
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (2709, 8, 'Omri Naftali', 'Adam Sandler is always funny', null);  # 2709 50 First Dates 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (79716, 7, 'Omri Naftali', 'decent action movie', null);  # 79716 Day After Tomorrow, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (187191, 6, 'Omri Naftali', 'funny, but nothing special', null);  # 187191 Legally Blonde 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (209591, 7, 'Omri Naftali', 'unique premise', null);  # 209591 Meet Joe Black 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (337814, 9, 'Omri Naftali', 'great police action', null);  # 337814 Training Day 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (63208, 10, 'Omri Naftali', 'iconic, visually stunning and incredible story telling', null);  # 63208 Chronicles of Narnia: The Lion, the Witch & the Wardrobe, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (235790, 7, 'Omri Naftali', 'charming and funny at times', null);  # 235790 Notting Hill 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (369458, 9, 'Omri Naftali', 'great superhero movie', null);  # 369458 X-Men 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (218415, 10, 'Omri Naftali', 'very funny movie', null);  # 218415 Monsters, Inc. 2001
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (151616, 8, 'Omri Naftali', 'stylish comedy', null);  # 151616 How to Lose a Guy in 10 Days 2003
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (194123, 8, 'Omri Naftali', 'Adam Sendler is great again', null);  # 194123 Longest Yard, The 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (87280, 8, 'Omri Naftali', 'romatic, fun and iconic', null);  # 87280 Dirty Dancing 1987
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (26846, 8, 'Omri Naftali', 'clever time travel', null);  # 26846 Back to the Future Part II 1989
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (40187, 9, 'Omri Naftali', 'great action movie', null);  # 40187 Blade 1998
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (41849, 5, 'Omri Naftali', 'some poor acting', null);  # 41849 Blue Lagoon, The 1980
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (166917, 9, 'Omri Naftali', 'heart-felt sports drama', null);  # 166917 Jerry Maguire 1996
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (50639, 7, 'Omri Naftali', 'dark take on time travel', null);  # 50639 Butterfly Effect, The 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (275453, 10, 'Omri Naftali', 'inspiring sports movie', null);  # 275453 Remember the Titans 2000
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (223799, 8, 'Omri Naftali', 'clever, sharp dialogue', null);  # 223799 My Cousin Vinny 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (16006, 9, 'Omri Naftali', 'stupid jokes, clever writing', null);  # 16006 Anchorman: The Legend of Ron Burgundy 2004
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (323813, 8, 'Omri Naftali', 'stylish and suspenseful', null);  # 323813 Talented Mr. Ripley, The 1999
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (177328, 7, 'Omri Naftali', 'great action, ok acting', null);  # 177328 King Kong 2005
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (289787, 9, 'Omri Naftali', 'stylish and heart-warming', null);  # 289787 Scent of a Woman 1992
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (155213, 10, 'Omri Naftali', 'funny, perfectlly written adventure film', null);  # 155213 Ice Age 2002
insert into personal_movies_ranking(movie_id, recommendation, suggested_by, justification, comment) values (362808, 8, 'Omri Naftali', 'charming and rewatchable', null);  # 362808 When Harry Met Sally... 1989